### ISSUE TITLE
Support for Metal Barrels

### ISSUE THREAD

**Issue by DNewman5** [Landmaster/InvTweaksReborn#12]
Adding support for this mod would be nice. It has almost 500k downloads.
https://www.curseforge.com/minecraft/mc-mods/metal-barrels

**Comment by Landmaster** [comment]
Post the full logs.

**Comment by mjlmjl888** [comment]
I think he means allow you to sort with them. You can't sort there inventory. You also can't sort https://www.curseforge.com/minecraft/mc-mods/better-crates.

**Comment by Landmaster** [comment]
What I mean is that when stuff like this happens, it normally logs an error without crashing the game. This happened with e.g. #4.

Also, is this for 1.15 only? (Since IIRC this issue was already fixed for 1.14)

**Comment by DNewman5** [comment]
It's 1.15 & forge-31.1.27. Just tested again with invtweaks-1.15.2-1.0.2, still not sorting and no log entries.
